version: "2"
services:

  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data

  flask:
    image: meowbot-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    command: uwsgi --ini instance/meowbot.ini
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis
    environment:
      - VIRTUAL_PROTO=uwsgi
      - VIRTUAL_HOST=meowbot.pbhuss.dev
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=meowbot.pbhuss.dev
    expose:
      - "5000"
    networks:
      - default
      - nginx-proxy

  worker:
    image: meowbot-flask
    command: rq worker -c instance.config
    volumes:
      - ./:/usr/src/app
    depends_on:
      - redis

  scheduler:
    image: meowbot-flask
    command: rqscheduler -H redis -i 10
    volumes:
    - ./:/usr/src/app
    depends_on:
      - redis

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
